@echo off
echo Starting Tranquility Backend Server...
cd tranquility-backend
echo Installing backend dependencies...
pip install -r requirements.txt
echo Starting FastAPI server...
python main.py
pause
