@echo off
echo Starting Tranquility Dashboard Server...
cd tranquility-app
echo Installing dependencies if needed...
call npm install
echo Opening browser...
start http://localhost:3000
echo Starting development server...
npm run dev
pause
